### ISSUE TITLE
Music Goes in and Out

### ISSUE THREAD

**Issue by simonk21** [mooreka21/CosmicWimpoutGameState#12]
During play, sometimes you hear music and sometimes you don’t.

**Comment by mooreka21** [comment]
This is an issue. I tried to fix this by putting the music on a continuous loop but the audio just layers over itself and ends up sounding awful. I also tried to put it in an if statement so that the music would only start playing the first time our updateDisplay method is called, but the music doesn't play at all in that case. I'm not really sure what to do at this point so it might be something we need to have Nuxoll look at.

**Comment by mooreka21** [comment]
We have fixed this so that the music plays consistently.

**Comment by simonk21** [comment]
Checked and the music is consistent. Good job! It's also a nice volume.
