### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by sugad21** [mooreka21/CosmicWimpoutGameState#2]
One thing was that a player can't end a game during the computer players turn. Also, out of curiosity, I went all the way up to 1400 something, so I inevitably whimped out, but during the computer players turn the human player was set to 150 points. Maybe I messed up a little, but it was unexpected.

**Comment by slemly** [comment]
The first issue is by design-at the moment, we are not allowing the players to perform actions

**Comment by dendinge21** [comment]
Legitimate bug, fix it by just allowing it to be legal. The other bug is illegitimate, they must be smart enough to end their turn when their turn score is a winning score.

**Comment by slemly** [comment]
The first issue is by design - we are currently not allowing players to perform actions when it is not their turn, but this is subject to change later. 
The second issue is also by design, due to when the scores are applied- the tallied score is only added to the player currently rolling is finished with their turn.

**Comment by sugad21** [comment]
okay can confirmed
